spring:
  profiles:
    active:
      - dev
---
server:
  port: 2001 #注册中心占用2001端口
spring:
  profiles: dev #开发环境
  application:
    name: kk-config-eureka
eureka:
  instance: 
    hostname: eureka2001.com #eureka服务端的实例名称
  client: 
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url: 
       defaultZone: http://eureka2001.com:2001/eureka/